# Change these first
owner: duino-coin # Your GitHub organization or username, where this repository lives
repo: status.duinocoin.com # The name of this repository

sites:
  - name: Homepage
    url: https://duinocoin.com
    icon: https://duinocoin.com/assets/icons/duco.svg
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: Masternodes
    url: https://server.duinocoin.com/api.json
    icon: https://duinocoin.com/assets/icons/duco.svg
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: APIs
    url: https://server.duinocoin.com/statistics
    icon: https://duinocoin.com/assets/icons/duco.svg
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: Web Wallet
    url: https://wallet.duinocoin.com
    icon: https://wallet.duinocoin.com/assets/duco.svg
  - name: Network stats & explorer
    url: https://explorer.duinocoin.com
    icon: https://explorer.duinocoin.com/assets/duco.svg
  - name: DUCO Exchange
    url: https://exchange.duinocoin.com
  - name: BSC Wrapper
    url: https://bsc.duinocoin.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  theme: night
  faviconSvg: https://raw.githubusercontent.com/duino-coin/status.duinocoin.com/gh-pages/duco.svg
  cname: status.duinocoin.com
  #baseUrl: /status.duinocoin.com
  logoUrl: https://raw.githubusercontent.com/duino-coin/status.duinocoin.com/gh-pages/duco.svg
  name: Duino-Coin Status
  introTitle: "**Duino-Coin Service Status**"
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Home
      href: https://duinocoin.com
    - title: Wallet
      href: https://wallet.duinocoin.com
    - title: Explorer
      href: https://explorer.duinocoin.com
    #- title: GitHub
    #  href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
