# Change these first
owner: duino-coin # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Duinocoin.com
    url: https://duinocoin.com
  - name: Duino-Coin API
    url: https://server.duinocoin.com/ping
    __dangerous__body_down_if_text_missing: '{"result":"Pong!","server":"master","success":true}'
  - name: Duino-Coin Wallet
    url: https://wallet.duinocoin.com
  - name: Duino-Coin Server
    url: https://server.duinocoin.com
  - name: Duino-Coin Explorer
    url: https://explorer.duinocoin.com
  - name: Duino-Coin Exchange
    url: https://exchange.duinocoin.com
  - name: Duino-Coin BSC Wrapper
    url: https://bsc.duinocoin.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.duinocoin.com
  # using duino-coin.github.io for testing cause cloudflare has a dns outage today
  #baseUrl: /status-page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Duino-Coin Status
  introTitle: "**Duino-Coin Service Status**"
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
